name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Remplacez par le nom de votre branche principale si nécessaire

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --prod --base-href=/PwaDemo/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/PwaDemo # Assurez-vous que le chemin correspond au répertoire de génération de votre application
